import eslintPluginAstro from "eslint-plugin-astro";
export default [
  { ignores: ["dist/"] },
  ...eslintPluginAstro.configs.recommended,
  {
    rules: {
      "arrow-body-style": "off",
      "astro/jsx-a11y/aria-proptypes": "error",
      "astro/jsx-a11y/aria-role": "error",
      "astro/no-set-html-directive": "error",
      "astro/no-set-text-directive": "error",
      "astro/sort-attributes": "error",
      curly: "off",
      "explicit-function-return-type": "off",
      "explicit-module-boundary-types": "off",
      "func-style": "off",
      "id-length": "off",
      "max-lines-per-function": "off",
      "max-statements": "off",
      "no-async-await": "off",
      "no-console": "off",
      "no-duplicate-imports": "off",
      "no-inline-comments": "off",
      "no-magic-numbers": "off",
      "no-map-spread": "off",
      "no-optional-chaining": "off",
      "no-rest-spread-properties": "off",
      "no-ternary": "off",
      "no-undef": "off",
      "no-unused-vars": "off",
      "no-void": "off",
      "prefer-destructuring": "off",
      "prefer-module": "off",
      "prefer-object-spread": "off",
      "prefer-spread": "off",
      "sort-imports": "error",
      "sort-keys": "off",
      "sort-vars": "off",
      "unicorn/no-array-for-each": "off",
      "unicorn/no-array-sort": "off",
      "unicorn/no-await-expression-member": "off",
      "unicorn/no-null": "off",
      "unicorn/prefer-global-this": "off",
      "unicorn/prefer-modern-dom-apis": "off",
      "unicorn/prefer-query-selector": "off",
      "unicorn/prefer-spread": "off",
    },
  },
];
